import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3c8e99'    
  },
  image: {
    flex: 1,
    justifyContent: "center"
  },
  inputContainer: {
    width: '80%',      
  },
  inputMail: {
    backgroundColor: ' rgba(194, 248, 203, 0.5);',
    borderLeftColor: 'black',
    borderLeftWidth: 4,
    borderTopColor: 'black',
    borderTopWidth: 4,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginTop: 5,
  },
  inputPassword: {
    backgroundColor: ' rgba(194, 248, 203, 0.5);',
    borderRightColor: 'black',
    borderRightWidth: 4,
    borderTopColor: 'black',
    borderTopWidth: 4,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginTop: 5,
  },
  inputImage: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
    alignItems: 'center',
    color: '#30321C',
  },
  buttonLogin: {
    backgroundColor: ' rgba(194, 248, 203, 0.5);',
    borderLeftColor: 'black',
    borderLeftWidth: 4,
    borderTopColor: 'black',
    borderTopWidth: 4,
    borderRadius: 5,
    marginTop: 20,
    margin: 5,
    width: '40%',
    height: '40%',
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
  }, 
  buttonRegister: {
    backgroundColor: ' rgba(194, 248, 203, 0.5);',
    borderLeftColor: 'black',
    borderLeftWidth: 4,
    borderBottomColor: 'black',
    borderBottomWidth: 4,
    borderRadius: 5,
    marginTop:20,
    margin: 5,
    height: '42%',
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonRole: {
    backgroundColor: ' rgba(194, 248, 203, 0.5);',
    borderRightColor: 'black',
    borderRightWidth: 4,
    borderBottomColor: 'black',
    borderBottomWidth: 4,
    borderRadius: 5,
    marginTop: 10,
    margin: 5,
    width: '100%',
    padding: 15,
    alignItems: 'center',
  },
  buttonText: {
    color: '#30321C',
    fontSize: 15,
    fontFamily: 'PermanentMarker_400Regular',
  },
  roleText: {
    color: '#30321C',
    fontSize: 12,
    fontFamily: 'PermanentMarker_400Regular',
  },
  footerText: {
    color: '#30321C',
    fontSize: 15,
    fontFamily: 'PermanentMarker_400Regular',
  },
  title: {
    fontSize: 40,
    marginBottom: 5,
    color: "black",
    fontFamily: 'PermanentMarker_400Regular',
  },
  body: {
    flex: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',    
  },
  footer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 10,
  },
  modalContainer: {
    flexDirection: "row",
    justifyContent: 'space-between',
  },
  modalBody: {
    borderColor: 'white',
    borderWidth: 2,
    width: '100%',
    padding: 15,
    borderRadius: 25,
    alignItems: 'center',
    flexDirection: "row",
    justifyContent: 'space-between',
  },
  modalText: {
    flexShrink: 1,
    fontSize: 20,
    fontWeight: 'bold',
    color: '#30321C',
    fontFamily: 'PermanentMarker_400Regular',
  },
  escapeButton: {
    backgroundColor: 'transparent',
    width: '25%',
    padding: 15,
    borderColor: 'transparent',
    borderWidth: 2,
    borderRadius: 25,
    alignItems: 'center',
  },
  faIcon: {
    color: '#30321C',
  }
});



